### PR TITLE
Updated File which can cause issues after minification.

### PR DESCRIPTION
**Pull request by mahad-apex**
I used this file in my project and I was minifying all my JS (by the handler, generically) but this file used "default" keyword which is reserved keyword.
So, in YUI JS minifier due to 'default' reserved keyword, it was breaking.
In code, there are several places where .default is used.
these are examples:
function () { return t.default }
function () { lt = document.body, re() }, !0); e.default = ee

### CODE REVIEW

**Comment by anseki** [comment]
Hi @mahad-apex, thank you for your PR.
Sorry, I couldn't understand this PR.
Why you replace the minified file? That is, the replacing is meaningless because the file is minified by building. And your file seems too big wastefully.
Also, the `default` is already reserved keyword by ECMAScript, and the code was added by Webpack. What is problem in YUI JS minifier?

**Comment by mahad-apex** [comment]
YUI JS minifier actually breaks when 'new' and 'default' used as variable. So in my case i changed 2 stances of .default to ["default"] in my PR.

**Comment by anseki** [comment]
- Do you mean that the `new` and `default` were used as variable (not property) in the file? Could you indicate where are those?
- Why did you try to re-minify the file that was already minified?

**Comment by mahad-apex** [comment]
Dear Anseki, your pluggin is great and we used in our application.
Find these lines in your minified version.
```
function () { return t.default }
function () { lt = document.body, re() }, !0); e.default = ee
```
The **.default** written in these lines can cause issues in minification.

Your point is absolutely right, there is no further need of minification of minified file, you can close PR!
In my case, there is a handler in C# we read generically all Js files either third party plugins or our functional JS and minify it once before dumping in page via handler, we dont use <script> tag. So your file was creating a problem so i fixed the issue by replacing the **e.default** to **e['default']** and it worked. So i thought i should inform you about **default** reserved keyword.

**Comment by anseki** [comment]
Unfortunately I cannot merge your PR:

- You seem to be misunderstanding the "variable". The both code `t.default` and `e.default` are not variable, those are "properties". Pay attention to each dot, the variable is written like `var default`.
- As I said, the `default` is already reserved by ECMAScript, then that has no problem. Also, of course the `default` property has no problem.
- As I said, the replacing is meaningless because the file is minified by build-script. This means that the file you fixed is overwritten every time.
- At least, if you really want to fix the minifying, you have to use source file, not minified file. Also, if you really want to remove the `default` property (not variable), you have to fix Webpack, not this library, because Webpack adds the `default` property.
- Your file seems too big wastefully. You changed all of code (not only `t.default` and `e.default`). See: https://github.com/anseki/plain-draggable/pull/28/commits/e5adad3b9f03718a5741551d81d41026d1c8c6e8 (Click "Load diff").
- You are calling "[YUI Compressor](https://yui.github.io/yuicompressor/)" "YUI JS minifier". Is it right? If so, you should not use YUI Compressor because that has [many problems](https://github.com/yui/yuicompressor/issues). Those seem to be including [some issues](https://github.com/yui/yuicompressor/issues?utf8=%E2%9C%93&q=is%3Aissue+%22missing+name+after+.+operator%22) related to your case. Also, that was already [thrown by Yahoo!](https://yahooeng.tumblr.com/post/96098168666/important-announcement-regarding-yui) and that was not updated by current contributors while [six years](https://github.com/yui/yuicompressor/issues/158). I strongly recommend another tool to minify such as [UglifyJS](http://lisperator.net/uglifyjs/).

Thank you for your time. :smile:

**Comment by mahad-apex** [comment]
Yes i got it.
Yes default is property,
YUI Compressor has many problems i have sent this feedback to architect already hopefully they will replace it with better alternative.
And yes i was wrong this file is built script so the change will be overwritten everytime.
I will see in webpack what i can do to replace this default. When i will start working 🙂

**Comment by anseki** [comment]
Maybe the problem is solved by replacing the minifying tool, instead of replacing the file.
Because this is a problem of YUI Compressor, not PlainDraggable, and not Webpack. i.e. Webpack also has no problem about the `default`.

**Pull request closed without merging**
